schema_version = "1.0.0"
id = "retarget"
name = "Retarget"
version = "2.9.0"
tagline = "Retargeting, convert to Rigify, Animation tools, Much more"
maintainer = "KBS DEV"
type = "add-on"
tags = ["Animation", "Rigging"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/KBSBAUDRICE/Retarget"
